matrix:
  include:
  - os: osx
    osx_image: xcode9.3
    language: node_js
    node_js: '6'
    env:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
addons:
  apt:
    packages:
    - clang
install:
- export CXX="clang++"
- npm install
cache:
  directories:
  - node_modules
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
before_install:
- |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v2.3.1/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-2.3.1.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1
    export PATH="/tmp/git-lfs:$PATH"
    brew install yarn
  fi
before_script:
- git lfs pull
script:
- npm run rebuildNative
- npm prune --production
- npm install -g electron-builder
- npm build
before_cache:
- rm -rf $HOME/.cache/electron-builder/wine
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
before_deploy:
  - git tag $(git log -n 1 --pretty=format:"%h")
deploy:
  provider: releases
  api_key:
    secure: U1veujpvfafAmw3dbkwqwibMFPpB/v7xybzw6QDR3TJZyviUWMKLvrSVYfJmQ9bk3Z60DgrsLDepNukx8EW7d1GKyy/5Ux7OnTZVtLuBv7MUS45tk5Ii0kBNGZU4Ma0U02S7o2aFvyWtKyf6pFUdcpNg+DkJPOgvT1LYpHeamTiQ3/h8W6Md3UFildBBTULzx153NXcus6Ns+PZZPZTfXOwUB2Y7x95X8H1JgRi4x21pUJZwI8OC62LY+2csN3eU4Saz6QVCNjh/apquANbg9LiPibCw0WWHcHGUw574fl3U/n//p8Jdvs7CJTxXMvxSHAuyG9NbvNG/XlzERgqgXVtozk6yuXBuIjdciaH0rrMINZlVp7y4mC8SlGIZY6dauRfr1PV24zlgRiqiLNTjii92YXXz89pOH2Jbk228XfkyrF1Oxy9gdSTXZReqVSMyUEWa/lGNNWZ6Bufr7Svewn5xklrLjkLXhmHhdBvCXuqIlYU0P2lNtrpv+/7AgxoELd8Pe86fG8tGbyrd+0F/1zYAai/ci4Fd++gZkuph4oBuHZTx5y1QU6Uz1HOaoCxFhsxUdDdxrcb9YIuoZ6cc/DycZ8MydTPnRP6gdXLBnWePCuGzCZlaW2L0H1cIPCt39EMalN6O5YAgPIgxtqYbwVq2U5cOMT5CAoHPrQ5KGU4=
  file: dist/*
  file_glob: true
  skip_cleanup: true
  on:
    repo: JieJiSS/Console-Lite
    tags: true
after_deploy:
- ls dist/
